Repository ember-engines/ember-engines, pull requests merged in 2021-01, with the labels that each got.

#741 Migrate to GitHub Actions for CI.
  .github/workflows/ci.yml
  .travis.yml
Labels: internal

#742 Fix compatibility with Ember 3.24+
  .github/workflows/ci.yml
  packages/ember-engines/addon/-private/engine-instance-ext.js
  packages/ember-engines/addon/components/link-to-component.js
  packages/ember-engines/addon/components/link-to-external.js
  packages/ember-engines/config/ember-try.js
  packages/ember-engines/package.json
  packages/ember-engines/tests/integration/component-with-link-to-external-test.js
  packages/ember-engines/tests/unit/components/link-to-external-test.js
  yarn.lock
Labels: bug

#743 Remove ember-compatibility-helpers.
  packages/ember-engines/package.json
  packages/ember-engines/tests/integration/component-with-link-to-external-test.js
  packages/ember-engines/tests/unit/components/link-to-external-test.js
  yarn.lock
Labels: internal

#744 Remove custom `<LinkTo />` override with Ember >= 3.24.1.
  packages/ember-engines/addon/-private/engine-ext.js
  packages/ember-engines/addon/components/link-to-component.js
Labels: enhancement

#745 Update the default ember-source version to 3.24.1.
  packages/ember-engines/package.json
  yarn.lock
Labels: internal

#752 Revert usage of `@embroider/macros`
  packages/ember-engines/addon/-private/engine-ext.js
  packages/ember-engines/addon/components/link-to-component.js
  packages/ember-engines/addon/components/link-to-external.js
  packages/ember-engines/package.json
  yarn.lock
Labels: bug

#750 Compute LCA host for engines
  packages/ember-engines/lib/engine-addon.js
  packages/ember-engines/lib/utils/find-hosts-host.js
  packages/ember-engines/lib/utils/find-lca-host.js
  packages/ember-engines/node-tests/fixtures/test-addons/addon-depends-on-lazy-engine/index.js
  packages/ember-engines/node-tests/fixtures/test-addons/addon-depends-on-lazy-engine/package.json
  packages/ember-engines/node-tests/fixtures/test-addons/lazy-engine-depends-on-lazy-engine/index.js
  packages/ember-engines/node-tests/fixtures/test-addons/lazy-engine-depends-on-lazy-engine/package.json
  packages/ember-engines/node-tests/fixtures/test-addons/test-lazy-engine/index.js
  packages/ember-engines/node-tests/fixtures/test-addons/test-lazy-engine/package.json
  packages/ember-engines/node-tests/fixtures/test-projects/common-lazy-engine-host/package.json
  packages/ember-engines/node-tests/fixtures/test-projects/lazy-engine-project-dep/package.json
  packages/ember-engines/node-tests/fixtures/test-projects/transitive-lazy-engine-project-dep/package.json
  packages/ember-engines/node-tests/unit/utils/find-lca-host-test.js
  packages/ember-engines/package.json
  yarn.lock
Labels: bug

#751 Ensure ember-engines are parallelizable.
  packages/ember-engines/ember-cli-build.js
Labels: internal
