Repository ember-engines/ember-engines, pull requests merged in 2022-04, with the labels that each got.

#804 Add exclude list to addon dedupe logic
  packages/ember-engines/lib/utils/deeply-non-duplicated-addon.js
Labels: bug

#797 Update to ember qunit 5
  .github/workflows/ci.yml
  packages/eager-blog/addon/templates/application.hbs
  packages/ember-engines/config/ember-try.js
  packages/ember-engines/node-tests/acceptance/build-test.js
  packages/ember-engines/package.json
  packages/ember-engines/tests/acceptance/lazy-routeable-engine-test.js
  packages/ember-engines/tests/acceptance/routeable-engine-demo-test.js
  packages/ember-engines/tests/acceptance/teardown-test.js
  packages/ember-engines/tests/dummy/config/optional-features.json
  packages/ember-engines/tests/helpers/destroy-app.js
  packages/ember-engines/tests/helpers/module-for-acceptance.js
  packages/ember-engines/tests/helpers/resolver.js
  packages/ember-engines/tests/helpers/start-app.js
  packages/ember-engines/tests/index.html
  packages/ember-engines/tests/unit/components/link-to-external-test.js
  packages/ember-engines/tests/unit/engine-instance-test.js
  packages/ember-engines/tests/unit/initializers/engines-test.js
  yarn.lock
Labels: internal

#798 Ember 4 compatibility
  .github/workflows/ci.yml
  packages/eager-blog/addon/templates/application.hbs
  packages/ember-blog/addon/templates/components/hello-name.hbs
  packages/ember-blog/addon/templates/index.hbs
  packages/ember-blog/addon/templates/post.hbs
  packages/ember-blog/addon/templates/post/comments.hbs
  packages/ember-blog/addon/templates/post/error.hbs
  packages/ember-chat/addon/templates/application.hbs
  packages/ember-chat/addon/templates/components/hello-world.hbs
  packages/ember-engines/addon/-private/engine-ext.js
  packages/ember-engines/addon/components/link-to-component.js
  packages/ember-engines/addon/components/link-to-external.js
  packages/ember-engines/config/ember-try.js
  packages/ember-engines/package.json
  packages/ember-engines/tests/integration/component-with-link-to-external-test.js
  packages/ember-engines/tests/unit/engine-instance-test.js
  packages/ember-engines/tests/unit/initializers/engines-test.js
Labels: enhancement
