Repository ember-engines/ember-engines, pull requests merged in 2024-04, with the labels that each got.

#872 Setup release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal

#869 Add more LTS version to CI matrix
  .github/workflows/ci.yml
  packages/ember-engines/config/ember-try.js
Labels: internal

#876 Ensure that the engine is destroyed in tests when the test context is cleaned up.
  packages/ember-engines/addon-test-support/index.js
  packages/ember-engines/tests/integration/setup-engine-test.js
Labels: bug

#868 Convert codebase to use native classes
  packages/common-components/addon/components/spanish-greeting.js
  packages/common-components/addon/templates/components/spanish-greeting.hbs
  packages/eager-blog/addon/engine.js
  packages/ember-blog/addon/components/hello-name.js
  packages/ember-blog/addon/controllers/post.js
  packages/ember-blog/addon/engine.js
  packages/ember-blog/addon/routes/application.js
  packages/ember-blog/addon/routes/index.js
  packages/ember-blog/addon/routes/new.js
  packages/ember-blog/addon/routes/post.js
  packages/ember-blog/addon/routes/post/comments.js
  packages/ember-blog/addon/routes/post/diggs.js
  packages/ember-blog/addon/routes/post/likes.js
  packages/ember-blog/addon/services/example-service.js
  packages/ember-blog/addon/templates/post.hbs
  packages/ember-chat/addon/components/hello-world.js
  packages/ember-chat/addon/controllers/application.js
  packages/ember-chat/addon/engine.js
  packages/ember-chat/addon/services/example-service.js
  packages/ember-chat/addon/templates/components/hello-world.hbs
  packages/ember-engines/blueprints/in-repo-engine/routable-files/lib/__name__/addon/engine.js
  packages/ember-engines/blueprints/in-repo-engine/routeless-files/lib/__name__/addon/engine.js
  packages/ember-engines/tests/dummy/app/controllers/post.js
  packages/ember-engines/tests/dummy/app/routes/routable-engine-demo/after-model.js
  packages/ember-engines/tests/dummy/app/routes/routable-engine-demo/normal-route.js
  packages/ember-engines/tests/dummy/app/routes/routable-engine-demo/redirect.js
  packages/ember-engines/tests/dummy/app/services/store.js
  packages/ember-engines/tests/integration/component-with-link-to-external-test.js
Labels: internal

#870 Drop support for Ember.js < 3.28
  .github/workflows/ci.yml
  packages/ember-engines/config/ember-try.js
Labels: breaking

#871 Colocate component templates
  packages/common-components/addon/components/spanish-greeting.hbs
  packages/common-components/addon/components/spanish-greeting.js
  packages/common-components/addon/templates/components/spanish-greeting.hbs
  packages/ember-blog/addon/components/hello-name.hbs
  packages/ember-blog/addon/components/hello-name.js
  packages/ember-blog/addon/components/hello-world.hbs
  packages/ember-blog/addon/components/magic-title/template.hbs
  packages/ember-blog/addon/components/pretty-color.hbs
  packages/ember-blog/addon/controllers/post.js
  packages/ember-blog/addon/routes/application.js
  packages/ember-blog/addon/templates/application.hbs
  packages/ember-blog/addon/templates/components/hello-name.hbs
  packages/ember-blog/addon/templates/new.hbs
  packages/ember-blog/addon/templates/post.hbs
  packages/ember-blog/package.json
  packages/ember-chat/addon/components/hello-world.hbs
  packages/ember-chat/addon/components/hello-world.js
  packages/ember-chat/addon/controllers/application.js
  packages/ember-chat/addon/templates/application.hbs
  packages/ember-engines/package.json
  packages/ember-engines/tests/dummy/app/controllers/.gitkeep
  pnpm-lock.yaml
Labels: internal

#878 Drop support for Ember.js < 3.28
  packages/ember-engines/package.json
Labels: breaking

#881 Replace ember-sinon with ember-sinon-qunit
  packages/ember-engines/node-tests/unit/engine-addon-test.js
  packages/ember-engines/package.json
  packages/ember-engines/tests/acceptance/routeable-engine-demo-test.js
  packages/ember-engines/tests/test-helper.js
  pnpm-lock.yaml
Labels: dependencies

#882 Bump node tests related packages
  packages/ember-engines/package.json
  pnpm-lock.yaml
Labels: internal, dependencies

#884 Bump eslint-plugin-qunit to v8 and fix errors
  packages/ember-engines/.eslintrc.js
  packages/ember-engines/package.json
  packages/ember-engines/tests/acceptance/lazy-routeable-engine-test.js
  packages/ember-engines/tests/acceptance/routeable-engine-demo-test.js
  packages/ember-engines/tests/acceptance/routeless-engine-demo-test.js
  packages/ember-engines/tests/acceptance/teardown-test.js
  packages/ember-engines/tests/integration/engine-resolver-test.js
  packages/ember-engines/tests/integration/setup-engine-test.js
  packages/ember-engines/tests/unit/components/link-to-external-test.js
  packages/ember-engines/tests/unit/engine-instance-test.js
  pnpm-lock.yaml
Labels: internal, dependencies

#885 run `npx ember-cli-update --to=5.7.0` to align with blueprint
  .github/workflows/ci.yml
  packages/ember-engines/.ember-cli
  packages/ember-engines/.npmignore
  packages/ember-engines/.watchmanconfig
  packages/ember-engines/CONTRIBUTING.md
  packages/ember-engines/README.md
  packages/ember-engines/addon-test-support/.eslintrc
  packages/ember-engines/addon/.eslintrc
  packages/ember-engines/addon/.gitkeep
  packages/ember-engines/app/.eslintrc
  packages/ember-engines/app/.gitkeep
  packages/ember-engines/config/environment.js
  packages/ember-engines/ember-cli-build.js
  packages/ember-engines/package.json
  packages/ember-engines/tests/dummy/app/index.html
  packages/ember-engines/tests/dummy/app/styles/app.css
  packages/ember-engines/tests/dummy/config/ember-cli-update.json
  packages/ember-engines/tests/dummy/config/ember-try.js
  packages/ember-engines/tests/dummy/config/environment.js
  packages/ember-engines/tests/dummy/config/targets.js
  packages/ember-engines/tests/helpers/index.js
  packages/ember-engines/tests/index.html
  packages/ember-engines/tsconfig.declarations.json
  pnpm-lock.yaml
Labels: internal

#886 Use same ESLint setup for /lib folder
  packages/ember-engines/.eslintrc.js
  packages/ember-engines/lib/.eslintrc.js
  packages/ember-engines/lib/engine-addon.js
  packages/ember-engines/lib/utils/append-compact-reexports-if-needed.js
  packages/ember-engines/lib/utils/deeply-non-duplicated-addon.js
  packages/ember-engines/lib/utils/find-host.js
  packages/ember-engines/lib/utils/find-lca-host.js
  packages/ember-engines/lib/utils/find-root.js
  packages/ember-engines/lib/utils/maybe-merge-trees.js
  packages/ember-engines/lib/utils/memoize.js
  packages/ember-engines/lib/utils/process-babel.js
  packages/ember-engines/lib/utils/restore-original-addons.js
Labels: internal

#888 [DEPRECATION] Deprecate transition methods of controller and route per RFC #674
  packages/ember-engines/addon/-private/controller-ext.js
  packages/ember-engines/addon/-private/deprecate-transition-methods.js
  packages/ember-engines/addon/-private/route-ext.js
  packages/ember-engines/tests/acceptance/routeable-engine-demo-test.js
Labels: enhancement
